# XF.Material
# Build a Xamarin.Android project.
# Build a Xamarin.iOS project.

jobs:
- job: Android
  pool:
    vmImage: 'VS2017-Win2016'
  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
      configuration: '$(buildConfiguration)'
      clean: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)'

- job: iOS
  pool:
    vmImage: 'macOS-10.13'
  variables:
    buildConfiguration: 'Release'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'
  - task: XamariniOS@2
    inputs:
      projectFile: '**/*iOS*.csproj'
      outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
      configuration: '$(buildConfiguration)'
      buildForSimulator: true
      packageApp: false
      clean: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)'
