name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Boots
        run : |
          dotnet tool install --global boots --prerelease
          boots --alpha Mono
          boots --alpha Xamarin.Android
        
      - name: Print Build Info
        run : |
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll --version
          dotnet --info
          
      - name: Build Android App
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./GitTrends.Android/GitTrends.Android.csproj /verbosity:normal /p:Configuration=Release /restore
          
    Build_UITests:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Build UITest Project
        run: |                    
          mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./GitTrends.UITests/GitTrends.UITests.csproj /verbosity:normal /p:Configuration=Release /restore

    Build_UnitTest_GitTrends:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Build Unit Tests
        run: |   
          UnitTestProject=`find . -name GitTrends.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet build  -c Release $UnitTestProject  
  
    Run_UnitTest_GitTrends:
      runs-on: macos-latest
      needs: [Build_Android, Build_UITests, Build_UnitTest_GitTrends]

      env:
        GetTestTokenApiKey: ${{ secrets.GetTestTokenApiKey }}
        GetAppCenterApiKeysKey: ${{ secrets.GetAppCenterApiKeysKey}}
        GetSyncFusionInformationApiKey: ${{ secrets.GetSyncFusionInformationApiKey }}
        GetNotificationHubInformationApiKey: ${{ secrets.GetNotificationHubInformationApiKey }}
        APPCENTER_SOURCE_DIRECTORY: .

      steps:
      - uses: actions/checkout@v1

      - name: Setup .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Inject API Keys
        run: |
          chmod -R 777 ./GitTrends.Android/appcenter-pre-build.sh
          ./GitTrends.Android/appcenter-pre-build.sh
          
      - name: Run Unit Tests
        run: |   
          UnitTestProject=`find . -name GitTrends.UnitTests.csproj`
          echo $UnitTestProject
          
          dotnet test  -c Release $UnitTestProject